branch-defaults:
  default:
    environment: luancv-project2
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  project2-luancv-imagefilter-dev:
    branch: null
    repository: null
global:
  application_name: project2-luancv-imagefilter
  branch: null
  default_ec2_keyname: AWS_EC2_DEMO
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
